load data 
infile 'admissionDrug.txt' "str '\n'"
replace
into table admissiondrug_new
fields terminated by '$!#'
OPTIONALLY ENCLOSED BY '"' AND '"'
trailing nullcols
           ( 
ADMISSIONDRUGID,
PATIENTUNITSTAYID,
DRUGYEAR,
DRUGTIME24,
DRUGTIME,
DRUGOFFSET,
DRUGENTEREDYEAR,
DRUGENTEREDTIME24,
DRUGENTEREDTIME,
DRUGENTEREDOFFSET,
DRUGNOTETYPE,
SPECIALTYTYPE,
USERTYPE,
RXINCLUDED,
WRITTENINEICU,
DRUGNAME,
DRUGDOSAGE,
DRUGUNIT,
DRUGADMITFREQUENCY,
DRUGHICLSEQNO,
PARTITIONKEY         

)
